In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math as math

In [2]:
Base_Vendas = [
    ["ID do Produto", "Produto", "Quantidade em Estoque", "Preço de Compra", "Preço de Venda", "Cor"],
    [1, "Arroz", 50, 20.00, 25.00, "Branco"],
    [2, "Feijão 1kg", 40, 7.00, 10.00, "Marrom"],
    [3, "Açúcar 1kg", 60, 4.50, 6.50, "Branco"],
    [4, "Óleo 900ml", 35, 8.00, 12.00, "Amarelo"],
    [5, "Leite 1L", 70, 2.00, 6.00, "Branco"],
    [6, "Café 500g", 30, 12.00, 18.00, "Preto"],
    [7, "Macarrão 500g", 55, 5.00, 7.00, "Bege"],
    [8, "Detergente 500ml", 80, 2.50, 4.00, "Azul"],
    [9, "Sabão", 45, 10.00, 15.00, "Azul"],
    [10, "Papel Higiênico", 90, 15.00, 23.00, "Branco"]
]

Base_Vendas

[['ID do Produto',
  'Produto',
  'Quantidade em Estoque',
  'Preço de Compra',
  'Preço de Venda',
  'Cor'],
 [1, 'Arroz', 50, 20.0, 25.0, 'Branco'],
 [2, 'Feijão 1kg', 40, 7.0, 10.0, 'Marrom'],
 [3, 'Açúcar 1kg', 60, 4.5, 6.5, 'Branco'],
 [4, 'Óleo 900ml', 35, 8.0, 12.0, 'Amarelo'],
 [5, 'Leite 1L', 70, 2.0, 6.0, 'Branco'],
 [6, 'Café 500g', 30, 12.0, 18.0, 'Preto'],
 [7, 'Macarrão 500g', 55, 5.0, 7.0, 'Bege'],
 [8, 'Detergente 500ml', 80, 2.5, 4.0, 'Azul'],
 [9, 'Sabão', 45, 10.0, 15.0, 'Azul'],
 [10, 'Papel Higiênico', 90, 15.0, 23.0, 'Branco']]

In [10]:
# Criando as matrizes A e B
A = np.array([[1, 2, 3],
              [5, 5, 9],
              [7, 34, 5]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Calculando a soma das matrizes
soma = A + B

# Exibindo o resultado
print("Matriz A:")
print(A)
print("\nMatriz B:")
print(B)
print("\nSoma (A + B):")
print(soma)

Matriz A:
[[ 1  2  3]
 [ 5  5  9]
 [ 7 34  5]]

Matriz B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Soma (A + B):
[[10 10 10]
 [11 10 13]
 [10 36  6]]


In [17]:
# Criando as matrizes A e B
A = np.array([[1, 2, 3],
              [5, 5, 9],
              [7, 34, 5]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Calculando a multiplicação das matrizes
mul = np.multiply(A, B)
# Exibindo o resultado
print("Matriz A:")
print(A)
print("\nMatriz B:")
print(B)
print("\Multiplicação (A * B):")
print(mul)

Matriz A:
[[ 1  2  3]
 [ 5  5  9]
 [ 7 34  5]]

Matriz B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]
\Multiplicação (A * B):
[[ 9 16 21]
 [30 25 36]
 [21 68  5]]


In [18]:
C = np.array([[1, 2], [3, 4], [5, 6]])

C_transposta = np.transpose(C)

# Exibindo o resultado
print("Matriz C:")
print(C)
print("\nTransposta da Matriz C:")
print(C_transposta)


Matriz C:
[[1 2]
 [3 4]
 [5 6]]

Transposta da Matriz C:
[[1 3 5]
 [2 4 6]]


In [19]:
A = np.array([[1, 2, 3],
              [5, 5, 9],
              [7, 34, 5]])

A_identidade = np.identity(len(A))

# Exibindo o resultado
print("Matriz A:")
print(A)
print("\nMatriz Identidade:")
print(A_identidade)

Matriz A:
[[ 1  2  3]
 [ 5  5  9]
 [ 7 34  5]]

Matriz Identidade:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
